# .github/workflows/issue-on-push.yml
on: [push]
name: Create an issue on push
permissions:
  contents: read
  issues: write 
jobs:
  get_filename:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jitterbit/get-changed-files@v1
        id: abc
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          ISSUE_TEMPLATE_FILENAME: ${{ steps.abc.outputs.added }}
      - run: echo "$ISSUE_TEMPLATE_FILENAME"
  stuff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JasonEtco/create-an-issue@v2.9.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: ${{ env.ISSUE_TEMPLATE_FILENAME }}
          #filename: .github/ISSUE_TEMPLATE/bug_report.md
